package com.modern.www._1_2_MySql_DB_entities;
// Generated Feb 20, 2021 9:15:52 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * A0003SubTabsId generated by hbm2java
 */
@Embeddable
public class A0003SubTabsId  implements java.io.Serializable {


     private int subTabId;
     private int tabId;
     private int mainTabId;

    public A0003SubTabsId() {
    }

    public A0003SubTabsId(int subTabId, int tabId, int mainTabId) {
       this.subTabId = subTabId;
       this.tabId = tabId;
       this.mainTabId = mainTabId;
    }
   


    @Column(name="sub_tab_id", nullable=false)
    public int getSubTabId() {
        return this.subTabId;
    }
    
    public void setSubTabId(int subTabId) {
        this.subTabId = subTabId;
    }


    @Column(name="tab_id", nullable=false)
    public int getTabId() {
        return this.tabId;
    }
    
    public void setTabId(int tabId) {
        this.tabId = tabId;
    }


    @Column(name="main_tab_id", nullable=false)
    public int getMainTabId() {
        return this.mainTabId;
    }
    
    public void setMainTabId(int mainTabId) {
        this.mainTabId = mainTabId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof A0003SubTabsId) ) return false;
		 A0003SubTabsId castOther = ( A0003SubTabsId ) other; 
         
		 return (this.getSubTabId()==castOther.getSubTabId())
 && (this.getTabId()==castOther.getTabId())
 && (this.getMainTabId()==castOther.getMainTabId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSubTabId();
         result = 37 * result + this.getTabId();
         result = 37 * result + this.getMainTabId();
         return result;
   }   


}


