package com.modern.www._1_2_MySql_DB_entities;
// Generated Mar 29, 2021 8:57:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * A0000TabsTypes generated by hbm2java
 */
@Entity
@Table(name="a_0_0_0_0_tabs_types"
    ,catalog="modern_web_site"
)
public class A0000TabsTypes  implements java.io.Serializable {


     private int tabTypeId;
     private String tabNameA;
     private String tabNameE;
     private Set<A0001MainTabs> a0001MainTabses = new HashSet<A0001MainTabs>(0);

    public A0000TabsTypes() {
    }

	
    public A0000TabsTypes(int tabTypeId, String tabNameA, String tabNameE) {
        this.tabTypeId = tabTypeId;
        this.tabNameA = tabNameA;
        this.tabNameE = tabNameE;
    }
    public A0000TabsTypes(int tabTypeId, String tabNameA, String tabNameE, Set<A0001MainTabs> a0001MainTabses) {
       this.tabTypeId = tabTypeId;
       this.tabNameA = tabNameA;
       this.tabNameE = tabNameE;
       this.a0001MainTabses = a0001MainTabses;
    }
   
     @Id 

    
    @Column(name="tab_type_id", unique=true, nullable=false)
    public int getTabTypeId() {
        return this.tabTypeId;
    }
    
    public void setTabTypeId(int tabTypeId) {
        this.tabTypeId = tabTypeId;
    }

    
    @Column(name="tab_name_a", nullable=false, length=45)
    public String getTabNameA() {
        return this.tabNameA;
    }
    
    public void setTabNameA(String tabNameA) {
        this.tabNameA = tabNameA;
    }

    
    @Column(name="tab_name_e", nullable=false, length=45)
    public String getTabNameE() {
        return this.tabNameE;
    }
    
    public void setTabNameE(String tabNameE) {
        this.tabNameE = tabNameE;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="a0000TabsTypes")
    public Set<A0001MainTabs> getA0001MainTabses() {
        return this.a0001MainTabses;
    }
    
    public void setA0001MainTabses(Set<A0001MainTabs> a0001MainTabses) {
        this.a0001MainTabses = a0001MainTabses;
    }




}


