package com.modern.www._1_2_MySql_DB_entities;
// Generated Mar 29, 2021 8:57:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * A0002Tabs generated by hbm2java
 */
@Entity
@Table(name="a_0_0_0_2_tabs"
    ,catalog="modern_web_site"
)
public class A0002Tabs  implements java.io.Serializable {


     private A0002TabsId id;
     private A0001MainTabs a0001MainTabs;
     private A0996Departments a0996Departments;
     private String tabNameA;
     private String tabNameE;
     private String iconFaFa;
     private String link;
     private Integer index1;
     private String tabLockedEnch;
     private Set<A0003SubTabs> a0003SubTabses = new HashSet<A0003SubTabs>(0);

    public A0002Tabs() {
    }

	
    public A0002Tabs(A0002TabsId id, A0001MainTabs a0001MainTabs, String tabNameA, String tabNameE, String tabLockedEnch) {
        this.id = id;
        this.a0001MainTabs = a0001MainTabs;
        this.tabNameA = tabNameA;
        this.tabNameE = tabNameE;
        this.tabLockedEnch = tabLockedEnch;
    }
    public A0002Tabs(A0002TabsId id, A0001MainTabs a0001MainTabs, A0996Departments a0996Departments, String tabNameA, String tabNameE, String iconFaFa, String link, Integer index1, String tabLockedEnch, Set<A0003SubTabs> a0003SubTabses) {
       this.id = id;
       this.a0001MainTabs = a0001MainTabs;
       this.a0996Departments = a0996Departments;
       this.tabNameA = tabNameA;
       this.tabNameE = tabNameE;
       this.iconFaFa = iconFaFa;
       this.link = link;
       this.index1 = index1;
       this.tabLockedEnch = tabLockedEnch;
       this.a0003SubTabses = a0003SubTabses;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="tabId", column=@Column(name="tab_id", nullable=false) ), 
        @AttributeOverride(name="mainTabId", column=@Column(name="main_tab_id", nullable=false) ) } )
    public A0002TabsId getId() {
        return this.id;
    }
    
    public void setId(A0002TabsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="main_tab_id", nullable=false, insertable=false, updatable=false)
    public A0001MainTabs getA0001MainTabs() {
        return this.a0001MainTabs;
    }
    
    public void setA0001MainTabs(A0001MainTabs a0001MainTabs) {
        this.a0001MainTabs = a0001MainTabs;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="department_id")
    public A0996Departments getA0996Departments() {
        return this.a0996Departments;
    }
    
    public void setA0996Departments(A0996Departments a0996Departments) {
        this.a0996Departments = a0996Departments;
    }

    
    @Column(name="tab_name_a", nullable=false, length=100)
    public String getTabNameA() {
        return this.tabNameA;
    }
    
    public void setTabNameA(String tabNameA) {
        this.tabNameA = tabNameA;
    }

    
    @Column(name="tab_name_e", nullable=false, length=100)
    public String getTabNameE() {
        return this.tabNameE;
    }
    
    public void setTabNameE(String tabNameE) {
        this.tabNameE = tabNameE;
    }

    
    @Column(name="icon_fa_fa", length=100)
    public String getIconFaFa() {
        return this.iconFaFa;
    }
    
    public void setIconFaFa(String iconFaFa) {
        this.iconFaFa = iconFaFa;
    }

    
    @Column(name="link")
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }

    
    @Column(name="index_1")
    public Integer getIndex1() {
        return this.index1;
    }
    
    public void setIndex1(Integer index1) {
        this.index1 = index1;
    }

    
    @Column(name="tab_locked_ench", nullable=false, length=50)
    public String getTabLockedEnch() {
        return this.tabLockedEnch;
    }
    
    public void setTabLockedEnch(String tabLockedEnch) {
        this.tabLockedEnch = tabLockedEnch;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="a0002Tabs")
    public Set<A0003SubTabs> getA0003SubTabses() {
        return this.a0003SubTabses;
    }
    
    public void setA0003SubTabses(Set<A0003SubTabs> a0003SubTabses) {
        this.a0003SubTabses = a0003SubTabses;
    }




}


