package com.modern.www._1_2_MySql_DB_entities;
// Generated Mar 29, 2021 8:57:57 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * A0003SubTabs generated by hbm2java
 */
@Entity
@Table(name="a_0_0_0_3_sub_tabs"
    ,catalog="modern_web_site"
)
public class A0003SubTabs  implements java.io.Serializable {


     private A0003SubTabsId id;
     private A0002Tabs a0002Tabs;
     private String subTabNameA;
     private String subTabNameE;
     private String iconFaFa;
     private String link;
     private int index1;

    public A0003SubTabs() {
    }

	
    public A0003SubTabs(A0003SubTabsId id, A0002Tabs a0002Tabs, String subTabNameA, String subTabNameE, int index1) {
        this.id = id;
        this.a0002Tabs = a0002Tabs;
        this.subTabNameA = subTabNameA;
        this.subTabNameE = subTabNameE;
        this.index1 = index1;
    }
    public A0003SubTabs(A0003SubTabsId id, A0002Tabs a0002Tabs, String subTabNameA, String subTabNameE, String iconFaFa, String link, int index1) {
       this.id = id;
       this.a0002Tabs = a0002Tabs;
       this.subTabNameA = subTabNameA;
       this.subTabNameE = subTabNameE;
       this.iconFaFa = iconFaFa;
       this.link = link;
       this.index1 = index1;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="subTabId", column=@Column(name="sub_tab_id", nullable=false) ), 
        @AttributeOverride(name="tabId", column=@Column(name="tab_id", nullable=false) ), 
        @AttributeOverride(name="mainTabId", column=@Column(name="main_tab_id", nullable=false) ) } )
    public A0003SubTabsId getId() {
        return this.id;
    }
    
    public void setId(A0003SubTabsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="tab_id", referencedColumnName="tab_id", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="main_tab_id", referencedColumnName="main_tab_id", nullable=false, insertable=false, updatable=false) } )
    public A0002Tabs getA0002Tabs() {
        return this.a0002Tabs;
    }
    
    public void setA0002Tabs(A0002Tabs a0002Tabs) {
        this.a0002Tabs = a0002Tabs;
    }

    
    @Column(name="sub_tab_name_a", nullable=false, length=100)
    public String getSubTabNameA() {
        return this.subTabNameA;
    }
    
    public void setSubTabNameA(String subTabNameA) {
        this.subTabNameA = subTabNameA;
    }

    
    @Column(name="sub_tab_name_e", nullable=false, length=100)
    public String getSubTabNameE() {
        return this.subTabNameE;
    }
    
    public void setSubTabNameE(String subTabNameE) {
        this.subTabNameE = subTabNameE;
    }

    
    @Column(name="icon_fa_fa", length=100)
    public String getIconFaFa() {
        return this.iconFaFa;
    }
    
    public void setIconFaFa(String iconFaFa) {
        this.iconFaFa = iconFaFa;
    }

    
    @Column(name="link")
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }

    
    @Column(name="index_1", nullable=false)
    public int getIndex1() {
        return this.index1;
    }
    
    public void setIndex1(int index1) {
        this.index1 = index1;
    }




}


