package com.modern.www._1_2_MySql_DB_entities;
// Generated Feb 20, 2021 9:15:52 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * A0050Levels generated by hbm2java
 */
@Entity
@Table(name="a_0_0_5_0_levels"
    ,catalog="modern_web_site"
)
public class A0050Levels  implements java.io.Serializable {


     private int levelId;
     private String levelNameA;
     private String levelNameE;
     private int index1;
     private Set<A0052Students> a0052Studentses = new HashSet<A0052Students>(0);

    public A0050Levels() {
    }

	
    public A0050Levels(int levelId, String levelNameA, String levelNameE, int index1) {
        this.levelId = levelId;
        this.levelNameA = levelNameA;
        this.levelNameE = levelNameE;
        this.index1 = index1;
    }
    public A0050Levels(int levelId, String levelNameA, String levelNameE, int index1, Set<A0052Students> a0052Studentses) {
       this.levelId = levelId;
       this.levelNameA = levelNameA;
       this.levelNameE = levelNameE;
       this.index1 = index1;
       this.a0052Studentses = a0052Studentses;
    }
   
     @Id 

    
    @Column(name="level_id", unique=true, nullable=false)
    public int getLevelId() {
        return this.levelId;
    }
    
    public void setLevelId(int levelId) {
        this.levelId = levelId;
    }

    
    @Column(name="level_name_a", nullable=false, length=100)
    public String getLevelNameA() {
        return this.levelNameA;
    }
    
    public void setLevelNameA(String levelNameA) {
        this.levelNameA = levelNameA;
    }

    
    @Column(name="level_name_e", nullable=false, length=100)
    public String getLevelNameE() {
        return this.levelNameE;
    }
    
    public void setLevelNameE(String levelNameE) {
        this.levelNameE = levelNameE;
    }

    
    @Column(name="index_1", nullable=false)
    public int getIndex1() {
        return this.index1;
    }
    
    public void setIndex1(int index1) {
        this.index1 = index1;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="a0050Levels")
    public Set<A0052Students> getA0052Studentses() {
        return this.a0052Studentses;
    }
    
    public void setA0052Studentses(Set<A0052Students> a0052Studentses) {
        this.a0052Studentses = a0052Studentses;
    }




}


