package com.modern.www._1_2_MySql_DB_entities;
// Generated Feb 20, 2021 9:15:52 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * A0056Complaints generated by hbm2java
 */
@Entity
@Table(name="a_0_0_5_6_complaints"
    ,catalog="modern_web_site"
)
public class A0056Complaints  implements java.io.Serializable {


     private A0056ComplaintsId id;
     private A0052Students a0052Students;
     private String complaintContent;
     private Date dateTime;

    public A0056Complaints() {
    }

    public A0056Complaints(A0056ComplaintsId id, A0052Students a0052Students, String complaintContent, Date dateTime) {
       this.id = id;
       this.a0052Students = a0052Students;
       this.complaintContent = complaintContent;
       this.dateTime = dateTime;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="complaintId", column=@Column(name="complaint_id", nullable=false) ), 
        @AttributeOverride(name="stdId", column=@Column(name="std_id", nullable=false) ) } )
    public A0056ComplaintsId getId() {
        return this.id;
    }
    
    public void setId(A0056ComplaintsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="std_id", nullable=false, insertable=false, updatable=false)
    public A0052Students getA0052Students() {
        return this.a0052Students;
    }
    
    public void setA0052Students(A0052Students a0052Students) {
        this.a0052Students = a0052Students;
    }

    
    @Column(name="complaint_content", nullable=false, length=200)
    public String getComplaintContent() {
        return this.complaintContent;
    }
    
    public void setComplaintContent(String complaintContent) {
        this.complaintContent = complaintContent;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_time", nullable=false, length=19)
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }




}


