package com.modern.www._1_2_MySql_DB_entities;
// Generated Mar 29, 2021 8:57:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * A0052Students generated by hbm2java
 */
@Entity
@Table(name="a_0_0_5_2_students"
    ,catalog="modern_web_site"
    , uniqueConstraints = {@UniqueConstraint(columnNames="std_personal_email"), @UniqueConstraint(columnNames="std_user_name")} 
)
public class A0052Students  implements java.io.Serializable {


     private int stdId;
     private A0050Levels a0050Levels;
     private A0051Lists a0051Lists;
     private A0996Departments a0996Departments;
     private String stdNameA;
     private String stdNameE;
     private String stdProfilePhoto;
     private String stdAcademicEmail;
     private String stdPersonalEmail;
     private String stdUserName;
     private String stdPassword;
     private Set<A0056Complaints> a0056Complaintses = new HashSet<A0056Complaints>(0);
     private Set<A0055StudentsCourses> a0055StudentsCourseses = new HashSet<A0055StudentsCourses>(0);

    public A0052Students() {
    }

	
    public A0052Students(int stdId, A0050Levels a0050Levels, A0051Lists a0051Lists, String stdNameA, String stdNameE, String stdAcademicEmail, String stdUserName, String stdPassword) {
        this.stdId = stdId;
        this.a0050Levels = a0050Levels;
        this.a0051Lists = a0051Lists;
        this.stdNameA = stdNameA;
        this.stdNameE = stdNameE;
        this.stdAcademicEmail = stdAcademicEmail;
        this.stdUserName = stdUserName;
        this.stdPassword = stdPassword;
    }
    public A0052Students(int stdId, A0050Levels a0050Levels, A0051Lists a0051Lists, A0996Departments a0996Departments, String stdNameA, String stdNameE, String stdProfilePhoto, String stdAcademicEmail, String stdPersonalEmail, String stdUserName, String stdPassword, Set<A0056Complaints> a0056Complaintses, Set<A0055StudentsCourses> a0055StudentsCourseses) {
       this.stdId = stdId;
       this.a0050Levels = a0050Levels;
       this.a0051Lists = a0051Lists;
       this.a0996Departments = a0996Departments;
       this.stdNameA = stdNameA;
       this.stdNameE = stdNameE;
       this.stdProfilePhoto = stdProfilePhoto;
       this.stdAcademicEmail = stdAcademicEmail;
       this.stdPersonalEmail = stdPersonalEmail;
       this.stdUserName = stdUserName;
       this.stdPassword = stdPassword;
       this.a0056Complaintses = a0056Complaintses;
       this.a0055StudentsCourseses = a0055StudentsCourseses;
    }
   
     @Id 

    
    @Column(name="std_id", unique=true, nullable=false)
    public int getStdId() {
        return this.stdId;
    }
    
    public void setStdId(int stdId) {
        this.stdId = stdId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="level_id", nullable=false)
    public A0050Levels getA0050Levels() {
        return this.a0050Levels;
    }
    
    public void setA0050Levels(A0050Levels a0050Levels) {
        this.a0050Levels = a0050Levels;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="list_id", nullable=false)
    public A0051Lists getA0051Lists() {
        return this.a0051Lists;
    }
    
    public void setA0051Lists(A0051Lists a0051Lists) {
        this.a0051Lists = a0051Lists;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="department_id")
    public A0996Departments getA0996Departments() {
        return this.a0996Departments;
    }
    
    public void setA0996Departments(A0996Departments a0996Departments) {
        this.a0996Departments = a0996Departments;
    }

    
    @Column(name="std_name_a", nullable=false, length=100)
    public String getStdNameA() {
        return this.stdNameA;
    }
    
    public void setStdNameA(String stdNameA) {
        this.stdNameA = stdNameA;
    }

    
    @Column(name="std_name_e", nullable=false, length=100)
    public String getStdNameE() {
        return this.stdNameE;
    }
    
    public void setStdNameE(String stdNameE) {
        this.stdNameE = stdNameE;
    }

    
    @Column(name="std_profile_photo")
    public String getStdProfilePhoto() {
        return this.stdProfilePhoto;
    }
    
    public void setStdProfilePhoto(String stdProfilePhoto) {
        this.stdProfilePhoto = stdProfilePhoto;
    }

    
    @Column(name="std_academic_email", nullable=false, length=100)
    public String getStdAcademicEmail() {
        return this.stdAcademicEmail;
    }
    
    public void setStdAcademicEmail(String stdAcademicEmail) {
        this.stdAcademicEmail = stdAcademicEmail;
    }

    
    @Column(name="std_personal_email", unique=true, length=100)
    public String getStdPersonalEmail() {
        return this.stdPersonalEmail;
    }
    
    public void setStdPersonalEmail(String stdPersonalEmail) {
        this.stdPersonalEmail = stdPersonalEmail;
    }

    
    @Column(name="std_user_name", unique=true, nullable=false, length=100)
    public String getStdUserName() {
        return this.stdUserName;
    }
    
    public void setStdUserName(String stdUserName) {
        this.stdUserName = stdUserName;
    }

    
    @Column(name="std_password", nullable=false, length=100)
    public String getStdPassword() {
        return this.stdPassword;
    }
    
    public void setStdPassword(String stdPassword) {
        this.stdPassword = stdPassword;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="a0052Students")
    public Set<A0056Complaints> getA0056Complaintses() {
        return this.a0056Complaintses;
    }
    
    public void setA0056Complaintses(Set<A0056Complaints> a0056Complaintses) {
        this.a0056Complaintses = a0056Complaintses;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="a0052Students")
    public Set<A0055StudentsCourses> getA0055StudentsCourseses() {
        return this.a0055StudentsCourseses;
    }
    
    public void setA0055StudentsCourseses(Set<A0055StudentsCourses> a0055StudentsCourseses) {
        this.a0055StudentsCourseses = a0055StudentsCourseses;
    }




}


