package com.modern.www._1_2_MySql_DB_entities;
// Generated Feb 20, 2021 9:15:52 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * A0054Courses generated by hbm2java
 */
@Entity
@Table(name="a_0_0_5_4_courses"
    ,catalog="modern_web_site"
)
public class A0054Courses  implements java.io.Serializable {


     private A0054CoursesId id;
     private A0051Lists a0051Lists;
     private A0053Course a0053Course;
     private int maxMidTerm;
     private Integer maxYearWork;
     private Integer maxLab;
     private Integer maxFinal;
     private Integer total;
     private Set<A0997TeachersTeachCourses> a0997TeachersTeachCourseses = new HashSet<A0997TeachersTeachCourses>(0);
     private Set<A0055StudentsCourses> a0055StudentsCourseses = new HashSet<A0055StudentsCourses>(0);

    public A0054Courses() {
    }

	
    public A0054Courses(A0054CoursesId id, A0051Lists a0051Lists, A0053Course a0053Course, int maxMidTerm) {
        this.id = id;
        this.a0051Lists = a0051Lists;
        this.a0053Course = a0053Course;
        this.maxMidTerm = maxMidTerm;
    }
    public A0054Courses(A0054CoursesId id, A0051Lists a0051Lists, A0053Course a0053Course, int maxMidTerm, Integer maxYearWork, Integer maxLab, Integer maxFinal, Integer total, Set<A0997TeachersTeachCourses> a0997TeachersTeachCourseses, Set<A0055StudentsCourses> a0055StudentsCourseses) {
       this.id = id;
       this.a0051Lists = a0051Lists;
       this.a0053Course = a0053Course;
       this.maxMidTerm = maxMidTerm;
       this.maxYearWork = maxYearWork;
       this.maxLab = maxLab;
       this.maxFinal = maxFinal;
       this.total = total;
       this.a0997TeachersTeachCourseses = a0997TeachersTeachCourseses;
       this.a0055StudentsCourseses = a0055StudentsCourseses;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="courseId", column=@Column(name="course_id", nullable=false) ), 
        @AttributeOverride(name="courseCode", column=@Column(name="course_code", nullable=false, length=10) ), 
        @AttributeOverride(name="listId", column=@Column(name="list_id", nullable=false) ) } )
    public A0054CoursesId getId() {
        return this.id;
    }
    
    public void setId(A0054CoursesId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="list_id", nullable=false, insertable=false, updatable=false)
    public A0051Lists getA0051Lists() {
        return this.a0051Lists;
    }
    
    public void setA0051Lists(A0051Lists a0051Lists) {
        this.a0051Lists = a0051Lists;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="course_id", nullable=false, insertable=false, updatable=false)
    public A0053Course getA0053Course() {
        return this.a0053Course;
    }
    
    public void setA0053Course(A0053Course a0053Course) {
        this.a0053Course = a0053Course;
    }

    
    @Column(name="max_mid_term", nullable=false)
    public int getMaxMidTerm() {
        return this.maxMidTerm;
    }
    
    public void setMaxMidTerm(int maxMidTerm) {
        this.maxMidTerm = maxMidTerm;
    }

    
    @Column(name="max_year_work")
    public Integer getMaxYearWork() {
        return this.maxYearWork;
    }
    
    public void setMaxYearWork(Integer maxYearWork) {
        this.maxYearWork = maxYearWork;
    }

    
    @Column(name="max_lab")
    public Integer getMaxLab() {
        return this.maxLab;
    }
    
    public void setMaxLab(Integer maxLab) {
        this.maxLab = maxLab;
    }

    
    @Column(name="max_final")
    public Integer getMaxFinal() {
        return this.maxFinal;
    }
    
    public void setMaxFinal(Integer maxFinal) {
        this.maxFinal = maxFinal;
    }

    
    @Column(name="total")
    public Integer getTotal() {
        return this.total;
    }
    
    public void setTotal(Integer total) {
        this.total = total;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="a0054Courses")
    public Set<A0997TeachersTeachCourses> getA0997TeachersTeachCourseses() {
        return this.a0997TeachersTeachCourseses;
    }
    
    public void setA0997TeachersTeachCourseses(Set<A0997TeachersTeachCourses> a0997TeachersTeachCourseses) {
        this.a0997TeachersTeachCourseses = a0997TeachersTeachCourseses;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="a0054Courses")
    public Set<A0055StudentsCourses> getA0055StudentsCourseses() {
        return this.a0055StudentsCourseses;
    }
    
    public void setA0055StudentsCourseses(Set<A0055StudentsCourses> a0055StudentsCourseses) {
        this.a0055StudentsCourseses = a0055StudentsCourseses;
    }




}


