package com.modern.www._1_2_MySql_DB_entities;
// Generated Mar 29, 2021 8:57:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * A0051Lists generated by hbm2java
 */
@Entity
@Table(name="a_0_0_5_1_lists"
    ,catalog="modern_web_site"
)
public class A0051Lists  implements java.io.Serializable {


     private int listId;
     private String listNameA;
     private String listNameE;
     private int index1;
     private Set<A0052Students> a0052Studentses = new HashSet<A0052Students>(0);
     private Set<A0054Courses> a0054Courseses = new HashSet<A0054Courses>(0);

    public A0051Lists() {
    }

	
    public A0051Lists(int listId, String listNameA, String listNameE, int index1) {
        this.listId = listId;
        this.listNameA = listNameA;
        this.listNameE = listNameE;
        this.index1 = index1;
    }
    public A0051Lists(int listId, String listNameA, String listNameE, int index1, Set<A0052Students> a0052Studentses, Set<A0054Courses> a0054Courseses) {
       this.listId = listId;
       this.listNameA = listNameA;
       this.listNameE = listNameE;
       this.index1 = index1;
       this.a0052Studentses = a0052Studentses;
       this.a0054Courseses = a0054Courseses;
    }
   
     @Id 

    
    @Column(name="list_id", unique=true, nullable=false)
    public int getListId() {
        return this.listId;
    }
    
    public void setListId(int listId) {
        this.listId = listId;
    }

    
    @Column(name="list_name_a", nullable=false, length=100)
    public String getListNameA() {
        return this.listNameA;
    }
    
    public void setListNameA(String listNameA) {
        this.listNameA = listNameA;
    }

    
    @Column(name="list_name_e", nullable=false, length=100)
    public String getListNameE() {
        return this.listNameE;
    }
    
    public void setListNameE(String listNameE) {
        this.listNameE = listNameE;
    }

    
    @Column(name="index_1", nullable=false)
    public int getIndex1() {
        return this.index1;
    }
    
    public void setIndex1(int index1) {
        this.index1 = index1;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="a0051Lists")
    public Set<A0052Students> getA0052Studentses() {
        return this.a0052Studentses;
    }
    
    public void setA0052Studentses(Set<A0052Students> a0052Studentses) {
        this.a0052Studentses = a0052Studentses;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="a0051Lists")
    public Set<A0054Courses> getA0054Courseses() {
        return this.a0054Courseses;
    }
    
    public void setA0054Courseses(Set<A0054Courses> a0054Courseses) {
        this.a0054Courseses = a0054Courseses;
    }




}


