package com.modern.www._1_2_MySql_DB_entities;
// Generated Mar 29, 2021 8:57:57 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * A0994DepartmentsManagers generated by hbm2java
 */
@Entity
@Table(name="a_0_9_9_4_departments_managers"
    ,catalog="modern_web_site"
)
public class A0994DepartmentsManagers  implements java.io.Serializable {


     private A0994DepartmentsManagersId id;
     private A0995DepartmentsManagmentType a0995DepartmentsManagmentType;
     private A0996Departments a0996Departments;
     private A0999Teachers a0999Teachers;
     private String note;

    public A0994DepartmentsManagers() {
    }

	
    public A0994DepartmentsManagers(A0994DepartmentsManagersId id, A0995DepartmentsManagmentType a0995DepartmentsManagmentType, A0996Departments a0996Departments, A0999Teachers a0999Teachers) {
        this.id = id;
        this.a0995DepartmentsManagmentType = a0995DepartmentsManagmentType;
        this.a0996Departments = a0996Departments;
        this.a0999Teachers = a0999Teachers;
    }
    public A0994DepartmentsManagers(A0994DepartmentsManagersId id, A0995DepartmentsManagmentType a0995DepartmentsManagmentType, A0996Departments a0996Departments, A0999Teachers a0999Teachers, String note) {
       this.id = id;
       this.a0995DepartmentsManagmentType = a0995DepartmentsManagmentType;
       this.a0996Departments = a0996Departments;
       this.a0999Teachers = a0999Teachers;
       this.note = note;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="managmentId", column=@Column(name="managment_id", nullable=false) ), 
        @AttributeOverride(name="departmentId", column=@Column(name="department_id", nullable=false) ), 
        @AttributeOverride(name="teacherId", column=@Column(name="teacher_id", nullable=false) ), 
        @AttributeOverride(name="mangmentDate", column=@Column(name="mangment_date", nullable=false, length=19) ) } )
    public A0994DepartmentsManagersId getId() {
        return this.id;
    }
    
    public void setId(A0994DepartmentsManagersId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="managment_id", nullable=false, insertable=false, updatable=false)
    public A0995DepartmentsManagmentType getA0995DepartmentsManagmentType() {
        return this.a0995DepartmentsManagmentType;
    }
    
    public void setA0995DepartmentsManagmentType(A0995DepartmentsManagmentType a0995DepartmentsManagmentType) {
        this.a0995DepartmentsManagmentType = a0995DepartmentsManagmentType;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="department_id", nullable=false, insertable=false, updatable=false)
    public A0996Departments getA0996Departments() {
        return this.a0996Departments;
    }
    
    public void setA0996Departments(A0996Departments a0996Departments) {
        this.a0996Departments = a0996Departments;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="teacher_id", nullable=false, insertable=false, updatable=false)
    public A0999Teachers getA0999Teachers() {
        return this.a0999Teachers;
    }
    
    public void setA0999Teachers(A0999Teachers a0999Teachers) {
        this.a0999Teachers = a0999Teachers;
    }

    
    @Column(name="note", length=100)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


