package com.modern.www._1_2_MySql_DB_entities;
// Generated Mar 29, 2021 8:57:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * A0998TeachersTypes generated by hbm2java
 */
@Entity
@Table(name="a_0_9_9_8_teachers_types"
    ,catalog="modern_web_site"
)
public class A0998TeachersTypes  implements java.io.Serializable {


     private int teacherTypeId;
     private String teacherTypeNameA;
     private String teacherTypeNameE;
     private Set<A0999Teachers> a0999Teacherses = new HashSet<A0999Teachers>(0);

    public A0998TeachersTypes() {
    }

	
    public A0998TeachersTypes(int teacherTypeId, String teacherTypeNameA, String teacherTypeNameE) {
        this.teacherTypeId = teacherTypeId;
        this.teacherTypeNameA = teacherTypeNameA;
        this.teacherTypeNameE = teacherTypeNameE;
    }
    public A0998TeachersTypes(int teacherTypeId, String teacherTypeNameA, String teacherTypeNameE, Set<A0999Teachers> a0999Teacherses) {
       this.teacherTypeId = teacherTypeId;
       this.teacherTypeNameA = teacherTypeNameA;
       this.teacherTypeNameE = teacherTypeNameE;
       this.a0999Teacherses = a0999Teacherses;
    }
   
     @Id 

    
    @Column(name="teacher_type_id", unique=true, nullable=false)
    public int getTeacherTypeId() {
        return this.teacherTypeId;
    }
    
    public void setTeacherTypeId(int teacherTypeId) {
        this.teacherTypeId = teacherTypeId;
    }

    
    @Column(name="teacher_type_name_a", nullable=false, length=45)
    public String getTeacherTypeNameA() {
        return this.teacherTypeNameA;
    }
    
    public void setTeacherTypeNameA(String teacherTypeNameA) {
        this.teacherTypeNameA = teacherTypeNameA;
    }

    
    @Column(name="teacher_type_name_e", nullable=false, length=45)
    public String getTeacherTypeNameE() {
        return this.teacherTypeNameE;
    }
    
    public void setTeacherTypeNameE(String teacherTypeNameE) {
        this.teacherTypeNameE = teacherTypeNameE;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="a0998TeachersTypes")
    public Set<A0999Teachers> getA0999Teacherses() {
        return this.a0999Teacherses;
    }
    
    public void setA0999Teacherses(Set<A0999Teachers> a0999Teacherses) {
        this.a0999Teacherses = a0999Teacherses;
    }




}


