package com.modern.www._1_2_MySql_DB_entities;
// Generated Mar 29, 2021 8:57:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * A0999Teachers generated by hbm2java
 */
@Entity
@Table(name="a_0_9_9_9_teachers"
    ,catalog="modern_web_site"
    , uniqueConstraints = @UniqueConstraint(columnNames="teacher_academic_email") 
)
public class A0999Teachers  implements java.io.Serializable {


     private int teacherId;
     private A0996Departments a0996Departments;
     private A0998TeachersTypes a0998TeachersTypes;
     private String teacherNameA;
     private String teacherNameE;
     private String teacherPhoto;
     private String teacherAcademicEmail;
     private String teacherPassword;
     private String teacherFacebook;
     private String teacherTwitter;
     private String teacherLinkedIn;
     private String teacherGooglePlus;
     private Set<A0996Departments> a0996DepartmentsesForHeadId = new HashSet<A0996Departments>(0);
     private Set<A0996Departments> a0996DepartmentsesForViceHeadId = new HashSet<A0996Departments>(0);
     private Set<A0994DepartmentsManagers> a0994DepartmentsManagerses = new HashSet<A0994DepartmentsManagers>(0);
     private Set<A0997TeachersTeachCourses> a0997TeachersTeachCourseses = new HashSet<A0997TeachersTeachCourses>(0);

    public A0999Teachers() {
    }

	
    public A0999Teachers(int teacherId, A0996Departments a0996Departments, A0998TeachersTypes a0998TeachersTypes, String teacherNameA, String teacherNameE, String teacherAcademicEmail, String teacherPassword) {
        this.teacherId = teacherId;
        this.a0996Departments = a0996Departments;
        this.a0998TeachersTypes = a0998TeachersTypes;
        this.teacherNameA = teacherNameA;
        this.teacherNameE = teacherNameE;
        this.teacherAcademicEmail = teacherAcademicEmail;
        this.teacherPassword = teacherPassword;
    }
    public A0999Teachers(int teacherId, A0996Departments a0996Departments, A0998TeachersTypes a0998TeachersTypes, String teacherNameA, String teacherNameE, String teacherPhoto, String teacherAcademicEmail, String teacherPassword, String teacherFacebook, String teacherTwitter, String teacherLinkedIn, String teacherGooglePlus, Set<A0996Departments> a0996DepartmentsesForHeadId, Set<A0996Departments> a0996DepartmentsesForViceHeadId, Set<A0994DepartmentsManagers> a0994DepartmentsManagerses, Set<A0997TeachersTeachCourses> a0997TeachersTeachCourseses) {
       this.teacherId = teacherId;
       this.a0996Departments = a0996Departments;
       this.a0998TeachersTypes = a0998TeachersTypes;
       this.teacherNameA = teacherNameA;
       this.teacherNameE = teacherNameE;
       this.teacherPhoto = teacherPhoto;
       this.teacherAcademicEmail = teacherAcademicEmail;
       this.teacherPassword = teacherPassword;
       this.teacherFacebook = teacherFacebook;
       this.teacherTwitter = teacherTwitter;
       this.teacherLinkedIn = teacherLinkedIn;
       this.teacherGooglePlus = teacherGooglePlus;
       this.a0996DepartmentsesForHeadId = a0996DepartmentsesForHeadId;
       this.a0996DepartmentsesForViceHeadId = a0996DepartmentsesForViceHeadId;
       this.a0994DepartmentsManagerses = a0994DepartmentsManagerses;
       this.a0997TeachersTeachCourseses = a0997TeachersTeachCourseses;
    }
   
     @Id 

    
    @Column(name="teacher_id", unique=true, nullable=false)
    public int getTeacherId() {
        return this.teacherId;
    }
    
    public void setTeacherId(int teacherId) {
        this.teacherId = teacherId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="department_id", nullable=false)
    public A0996Departments getA0996Departments() {
        return this.a0996Departments;
    }
    
    public void setA0996Departments(A0996Departments a0996Departments) {
        this.a0996Departments = a0996Departments;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="teacher_type_id", nullable=false)
    public A0998TeachersTypes getA0998TeachersTypes() {
        return this.a0998TeachersTypes;
    }
    
    public void setA0998TeachersTypes(A0998TeachersTypes a0998TeachersTypes) {
        this.a0998TeachersTypes = a0998TeachersTypes;
    }

    
    @Column(name="teacher_name_a", nullable=false, length=100)
    public String getTeacherNameA() {
        return this.teacherNameA;
    }
    
    public void setTeacherNameA(String teacherNameA) {
        this.teacherNameA = teacherNameA;
    }

    
    @Column(name="teacher_name_e", nullable=false, length=100)
    public String getTeacherNameE() {
        return this.teacherNameE;
    }
    
    public void setTeacherNameE(String teacherNameE) {
        this.teacherNameE = teacherNameE;
    }

    
    @Column(name="teacher_photo")
    public String getTeacherPhoto() {
        return this.teacherPhoto;
    }
    
    public void setTeacherPhoto(String teacherPhoto) {
        this.teacherPhoto = teacherPhoto;
    }

    
    @Column(name="teacher_academic_email", unique=true, nullable=false, length=100)
    public String getTeacherAcademicEmail() {
        return this.teacherAcademicEmail;
    }
    
    public void setTeacherAcademicEmail(String teacherAcademicEmail) {
        this.teacherAcademicEmail = teacherAcademicEmail;
    }

    
    @Column(name="teacher_password", nullable=false, length=100)
    public String getTeacherPassword() {
        return this.teacherPassword;
    }
    
    public void setTeacherPassword(String teacherPassword) {
        this.teacherPassword = teacherPassword;
    }

    
    @Column(name="teacher_facebook", length=200)
    public String getTeacherFacebook() {
        return this.teacherFacebook;
    }
    
    public void setTeacherFacebook(String teacherFacebook) {
        this.teacherFacebook = teacherFacebook;
    }

    
    @Column(name="teacher_twitter", length=200)
    public String getTeacherTwitter() {
        return this.teacherTwitter;
    }
    
    public void setTeacherTwitter(String teacherTwitter) {
        this.teacherTwitter = teacherTwitter;
    }

    
    @Column(name="teacher_linked_in", length=200)
    public String getTeacherLinkedIn() {
        return this.teacherLinkedIn;
    }
    
    public void setTeacherLinkedIn(String teacherLinkedIn) {
        this.teacherLinkedIn = teacherLinkedIn;
    }

    
    @Column(name="teacher_google_plus", length=200)
    public String getTeacherGooglePlus() {
        return this.teacherGooglePlus;
    }
    
    public void setTeacherGooglePlus(String teacherGooglePlus) {
        this.teacherGooglePlus = teacherGooglePlus;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="a0999TeachersByHeadId")
    public Set<A0996Departments> getA0996DepartmentsesForHeadId() {
        return this.a0996DepartmentsesForHeadId;
    }
    
    public void setA0996DepartmentsesForHeadId(Set<A0996Departments> a0996DepartmentsesForHeadId) {
        this.a0996DepartmentsesForHeadId = a0996DepartmentsesForHeadId;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="a0999TeachersByViceHeadId")
    public Set<A0996Departments> getA0996DepartmentsesForViceHeadId() {
        return this.a0996DepartmentsesForViceHeadId;
    }
    
    public void setA0996DepartmentsesForViceHeadId(Set<A0996Departments> a0996DepartmentsesForViceHeadId) {
        this.a0996DepartmentsesForViceHeadId = a0996DepartmentsesForViceHeadId;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="a0999Teachers")
    public Set<A0994DepartmentsManagers> getA0994DepartmentsManagerses() {
        return this.a0994DepartmentsManagerses;
    }
    
    public void setA0994DepartmentsManagerses(Set<A0994DepartmentsManagers> a0994DepartmentsManagerses) {
        this.a0994DepartmentsManagerses = a0994DepartmentsManagerses;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="a0999Teachers")
    public Set<A0997TeachersTeachCourses> getA0997TeachersTeachCourseses() {
        return this.a0997TeachersTeachCourseses;
    }
    
    public void setA0997TeachersTeachCourseses(Set<A0997TeachersTeachCourses> a0997TeachersTeachCourseses) {
        this.a0997TeachersTeachCourseses = a0997TeachersTeachCourseses;
    }




}


