package com.modern.www._1_2_MySql_DB_entities;
// Generated Feb 20, 2021 9:15:52 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * A0994DepartmentsManagersId generated by hbm2java
 */
@Embeddable
public class A0994DepartmentsManagersId  implements java.io.Serializable {


     private int managmentId;
     private int departmentId;
     private int teacherId;
     private Date mangmentDate;

    public A0994DepartmentsManagersId() {
    }

    public A0994DepartmentsManagersId(int managmentId, int departmentId, int teacherId, Date mangmentDate) {
       this.managmentId = managmentId;
       this.departmentId = departmentId;
       this.teacherId = teacherId;
       this.mangmentDate = mangmentDate;
    }
   


    @Column(name="managment_id", nullable=false)
    public int getManagmentId() {
        return this.managmentId;
    }
    
    public void setManagmentId(int managmentId) {
        this.managmentId = managmentId;
    }


    @Column(name="department_id", nullable=false)
    public int getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(int departmentId) {
        this.departmentId = departmentId;
    }


    @Column(name="teacher_id", nullable=false)
    public int getTeacherId() {
        return this.teacherId;
    }
    
    public void setTeacherId(int teacherId) {
        this.teacherId = teacherId;
    }


    @Column(name="mangment_date", nullable=false, length=19)
    public Date getMangmentDate() {
        return this.mangmentDate;
    }
    
    public void setMangmentDate(Date mangmentDate) {
        this.mangmentDate = mangmentDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof A0994DepartmentsManagersId) ) return false;
		 A0994DepartmentsManagersId castOther = ( A0994DepartmentsManagersId ) other; 
         
		 return (this.getManagmentId()==castOther.getManagmentId())
 && (this.getDepartmentId()==castOther.getDepartmentId())
 && (this.getTeacherId()==castOther.getTeacherId())
 && ( (this.getMangmentDate()==castOther.getMangmentDate()) || ( this.getMangmentDate()!=null && castOther.getMangmentDate()!=null && this.getMangmentDate().equals(castOther.getMangmentDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getManagmentId();
         result = 37 * result + this.getDepartmentId();
         result = 37 * result + this.getTeacherId();
         result = 37 * result + ( getMangmentDate() == null ? 0 : this.getMangmentDate().hashCode() );
         return result;
   }   


}


