package com.modern.www._1_2_MySql_DB_entities;
// Generated Feb 20, 2021 9:15:52 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * A0996Departments generated by hbm2java
 */
@Entity
@Table(name="a_0_9_9_6_departments"
    ,catalog="modern_web_site"
)
public class A0996Departments  implements java.io.Serializable {


     private int departmentId;
     private A0999Teachers a0999TeachersByHeadId;
     private A0999Teachers a0999TeachersByViceHeadId;
     private String departmentNameA;
     private String departmentNameE;
     private Integer departmentIndex;
     private Set<A0999Teachers> a0999Teacherses = new HashSet<A0999Teachers>(0);
     private Set<A0994DepartmentsManagers> a0994DepartmentsManagerses = new HashSet<A0994DepartmentsManagers>(0);
     private Set<A0053Course> a0053Courses = new HashSet<A0053Course>(0);
     private Set<A0002Tabs> a0002Tabses = new HashSet<A0002Tabs>(0);

    public A0996Departments() {
    }

	
    public A0996Departments(int departmentId, String departmentNameA, String departmentNameE) {
        this.departmentId = departmentId;
        this.departmentNameA = departmentNameA;
        this.departmentNameE = departmentNameE;
    }
    public A0996Departments(int departmentId, A0999Teachers a0999TeachersByHeadId, A0999Teachers a0999TeachersByViceHeadId, String departmentNameA, String departmentNameE, Integer departmentIndex, Set<A0999Teachers> a0999Teacherses, Set<A0994DepartmentsManagers> a0994DepartmentsManagerses, Set<A0053Course> a0053Courses, Set<A0002Tabs> a0002Tabses) {
       this.departmentId = departmentId;
       this.a0999TeachersByHeadId = a0999TeachersByHeadId;
       this.a0999TeachersByViceHeadId = a0999TeachersByViceHeadId;
       this.departmentNameA = departmentNameA;
       this.departmentNameE = departmentNameE;
       this.departmentIndex = departmentIndex;
       this.a0999Teacherses = a0999Teacherses;
       this.a0994DepartmentsManagerses = a0994DepartmentsManagerses;
       this.a0053Courses = a0053Courses;
       this.a0002Tabses = a0002Tabses;
    }
   
     @Id 

    
    @Column(name="department_id", unique=true, nullable=false)
    public int getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(int departmentId) {
        this.departmentId = departmentId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="head_id")
    public A0999Teachers getA0999TeachersByHeadId() {
        return this.a0999TeachersByHeadId;
    }
    
    public void setA0999TeachersByHeadId(A0999Teachers a0999TeachersByHeadId) {
        this.a0999TeachersByHeadId = a0999TeachersByHeadId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="vice_head_id")
    public A0999Teachers getA0999TeachersByViceHeadId() {
        return this.a0999TeachersByViceHeadId;
    }
    
    public void setA0999TeachersByViceHeadId(A0999Teachers a0999TeachersByViceHeadId) {
        this.a0999TeachersByViceHeadId = a0999TeachersByViceHeadId;
    }

    
    @Column(name="department_name_a", nullable=false, length=100)
    public String getDepartmentNameA() {
        return this.departmentNameA;
    }
    
    public void setDepartmentNameA(String departmentNameA) {
        this.departmentNameA = departmentNameA;
    }

    
    @Column(name="department_name_e", nullable=false, length=100)
    public String getDepartmentNameE() {
        return this.departmentNameE;
    }
    
    public void setDepartmentNameE(String departmentNameE) {
        this.departmentNameE = departmentNameE;
    }

    
    @Column(name="department_index")
    public Integer getDepartmentIndex() {
        return this.departmentIndex;
    }
    
    public void setDepartmentIndex(Integer departmentIndex) {
        this.departmentIndex = departmentIndex;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="a0996Departments")
    public Set<A0999Teachers> getA0999Teacherses() {
        return this.a0999Teacherses;
    }
    
    public void setA0999Teacherses(Set<A0999Teachers> a0999Teacherses) {
        this.a0999Teacherses = a0999Teacherses;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="a0996Departments")
    public Set<A0994DepartmentsManagers> getA0994DepartmentsManagerses() {
        return this.a0994DepartmentsManagerses;
    }
    
    public void setA0994DepartmentsManagerses(Set<A0994DepartmentsManagers> a0994DepartmentsManagerses) {
        this.a0994DepartmentsManagerses = a0994DepartmentsManagerses;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="a0996Departments")
    public Set<A0053Course> getA0053Courses() {
        return this.a0053Courses;
    }
    
    public void setA0053Courses(Set<A0053Course> a0053Courses) {
        this.a0053Courses = a0053Courses;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="a0996Departments")
    public Set<A0002Tabs> getA0002Tabses() {
        return this.a0002Tabses;
    }
    
    public void setA0002Tabses(Set<A0002Tabs> a0002Tabses) {
        this.a0002Tabses = a0002Tabses;
    }




}


