package com.modern.www._1_2_MySql_DB_entities;
// Generated Feb 20, 2021 9:15:52 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * A9999AdminUsers generated by hbm2java
 */
@Entity
@Table(name="a_9_9_9_9_admin_users"
    ,catalog="modern_web_site"
)
public class A9999AdminUsers  implements java.io.Serializable {


     private int userId;
     private A9999AdminUsers a9999AdminUsers;
     private String userName;
     private String userUserName;
     private String userPassword;
     private Set<A9999AdminUsers> a9999AdminUserses = new HashSet<A9999AdminUsers>(0);

    public A9999AdminUsers() {
    }

	
    public A9999AdminUsers(int userId, String userName, String userUserName, String userPassword) {
        this.userId = userId;
        this.userName = userName;
        this.userUserName = userUserName;
        this.userPassword = userPassword;
    }
    public A9999AdminUsers(int userId, A9999AdminUsers a9999AdminUsers, String userName, String userUserName, String userPassword, Set<A9999AdminUsers> a9999AdminUserses) {
       this.userId = userId;
       this.a9999AdminUsers = a9999AdminUsers;
       this.userName = userName;
       this.userUserName = userUserName;
       this.userPassword = userPassword;
       this.a9999AdminUserses = a9999AdminUserses;
    }
   
     @Id 

    
    @Column(name="user_id", unique=true, nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="registered_user_id")
    public A9999AdminUsers getA9999AdminUsers() {
        return this.a9999AdminUsers;
    }
    
    public void setA9999AdminUsers(A9999AdminUsers a9999AdminUsers) {
        this.a9999AdminUsers = a9999AdminUsers;
    }

    
    @Column(name="user_name", nullable=false, length=100)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="user_user_name", nullable=false, length=100)
    public String getUserUserName() {
        return this.userUserName;
    }
    
    public void setUserUserName(String userUserName) {
        this.userUserName = userUserName;
    }

    
    @Column(name="user_password", nullable=false, length=200)
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="a9999AdminUsers")
    public Set<A9999AdminUsers> getA9999AdminUserses() {
        return this.a9999AdminUserses;
    }
    
    public void setA9999AdminUserses(Set<A9999AdminUsers> a9999AdminUserses) {
        this.a9999AdminUserses = a9999AdminUserses;
    }




}


